config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :discussions
    resources :memberships, only: [:create, :destroy]
  end

  namespace :discussions do
    resources :comments
  end

  post "/tasks/status_change/:id" => "tasks#status_change", as: :status_change_task

  get "/about" => "home#about"

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "home#index"

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project
  belongs_to :user;

  has_many :comments, dependent: :destroy
  validates :title, presence: true

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  # trying to be more explicit in each controller actions
  # that we need project associated with the discussion
  # in code, instead of having multiple before_actions
  # before_action :find_project
  # before_action :find_discussion, only: [:show, :edit, :update, :destroy]

  def new
    @project = Project.find params[:project_id]
    @discussion = Discussion.new
  end

  def create
    @project = Project.find params[:project_id]
    @discussion = Discussion.new(discussion_params)

    # assign discussion to project
    @discussion.project = @project

    if @discussion.save
      #render text: "SUCCESS"
      redirect_to project_discussions_path(@project), notice: "Discussion created"
    else
      #render text: "FAILURE"
      flash[:alert] = "Discussion not created"
      render "projects/show"
    end
  end

  def edit
    @project = Project.find params[:project_id]
    @discussion = @project.discussions.find params[:id]
  end

  def update
    @project = Project.find params[:project_id]
    @discussion = @project.discussions.find params[:id]
    if @discussion.update discussion_params
      redirect_to project_discussion_path(@project, @discussion), notice: "Discussion updated"
    else
      render :edit
    end

  end

  def index
    # show only the discussion for the particular projects
    @project = Project.find params[:project_id]
    @discussions = @project.discussions

    # allow for creation of new discussion on the index page of discussions
    @discussion = Discussion.new
  end

  def show
    @project = Project.find params[:project_id]
    @discussion = @project.discussions.find params[:id]
    @comment = Comment.new
    # puts "===================== inside discussion controller show"
  end

  def destroy
    @project = Project.find params[:project_id]
    discussion = @project.discussions.find params[:id]
    discussion.destroy
    redirect_to project_discussions_path(@project), notice: "Discussion deleted!"

  end


private

  def discussion_params
    discussion_params = params.require(:discussion).permit([:title, :body])
  end

  # def find_project
  #   @project = Project.find_by params[:project_id]
  #   # redirect_to projects_path, alert: "No project found for this discussion" if @project == nil
  #   # puts "===================== after redirect_to_projects_path"
  # end

  # def find_discussion
  #   @discussion = Discussion.find params[:id]
  # end


end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_for [@project, @discussion], html: {class: "form"} do |f| %>
 <div class="form-group">
   <%= f.label :title, "Title", class: "control-label" %>
   <%= f.text_area :title, class: "form-control" %>
 </div>

 <div class="form-group project-discussion">
   <%= f.label :body, "Body", class: "control-label" %>
   <%= f.text_area :body, class: "form-control project-discussion__textarea" %>
 </div>

 <div class="form-group">
   <%= f.submit submit_text, class: "btn btn-primary" %>
 </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Edit Discussion</h1>

<%= render partial: "form", locals: { submit_text: 'Update Discussion' } %>

app/views/discussions/index.html.erb
<h1>Discussions for Project: <%= @project.title %></h1>
<hr>
<% @discussions.each do |discussion| %>
  <div>
    <%= link_to discussion.title, project_discussion_path(@project, discussion) %>
  </div>
<% end %>
<br>
<%= link_to "Back to Project", project_path(@project) %>
<hr>
<%# new discussion form %>
<h2>New Discussion</h2>
<%= render partial: "form", locals: { submit_text: 'Create Discussion' } %>

app/views/discussions/show.html.erb
<h1> Project Discussion: <%= @discussion.project.title %></h1>
<h2><%= @discussion.title %></h1>
<p><%= @discussion.body %></p>
<%= link_to "Edit", edit_project_discussion_path(@discussion.project, @discussion) %>
|
<%= link_to "Delete", project_discussion_path(@discussion.project, @discussion), method: :delete,
                                  data: {confirm: "Are you sure?"}%>
|
<%= link_to "Back to Discussions", project_discussions_path(@discussion.project) %>
|
<%= link_to "Back to Project", project_path(@discussion.project) %>


<hr>
<%= @comment.errors.full_messages.join(", ") %>
<hr>

<h2>Comments</h2>
<%# partil review is defined in review/_review.html.erb %>
<%= render @discussion.comments.order('created_at DESC') %>

<h2>New Comment</h2>
<%= form_for @comment, url: discussion_comments_path(@discussion), html: {class: "form"} do |f| %>

  <div class="form-group discussion-comment">
    <%= f.label :body, "Comment", class: "control-label" %>
    <%= f.text_area :body, class: "form-control discussion-comment__textarea" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Comment", class: "btn btn-primary" %>
  </div>
<% end %>

</div>