config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :discussions
    resources :memberships, only: [:create, :destroy]
  end

  namespace :discussions do
    resources :comments
  end

  post "/tasks/status_change/:id" => "tasks#status_change", as: :status_change_task

  get "/about" => "home#about"

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true, uniqueness: {scope: :project_id}
  belongs_to :project
  belongs_to :user;

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end


  def create
    @project = Project.find params[:project_id]

    task_params = params.require(:task).permit(:title, :body, :due_date)
    @task = Task.new(task_params)

    # important association
    @task.project = @project


    if @task.save
      #render text: "SUCCESS"
      redirect_to project_path(@project), notice: "Task created"
    else
      #render text: "FAILURE"
      flash[:alert] = "Task is not saved"
      render "projects/show"
    end
  end

  def show
    @task = Task.find params[:id]
  end

  def index
    @tasks = Task.all
  end


  def edit
    @project = Project.find params[:project_id]
    #puts "===== project_id: #{@project.id} ===="

    @task = Task.find params[:id]
    #puts "===== task_id: #{@task.id} ===="
  end

  def update
    @task = Task.find params[:id]
    task_params = params.require(:task).permit([:title, :body, :due_date])

    if @task.update task_params
      redirect_to project_path(@task.project)
    else
      render :edit
    end
  end

  def destroy
    project = Project.find params[:project_id]

    @task = Task.find params[:id]
    @task.destroy
    redirect_to project_path(@task.project), notice: "Task deleted"
  end

  def status_change

    @task = Task.find params[:id]

    if @task.status == 'Not Done'
       @task.status = 'Done'
    elsif @task.status == 'Done'
      @task.status = 'Not Done'
    else
      @task.status = 'Not Done'
    end

    @task.save

    redirect_to project_path(@task.project)

  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= @task.errors.full_messages.join(", ") %>

<%= form_for @task, url: project_task_path(@project, @task), method: :patch do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.label :due_date %>
    <%= f.datetime_field :due_date %>
  </div>

  <%= f.submit %>

<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
<% @tasks.each do |task| %>
  <div>
    <%= link_to "project #{task.project_id}: " + task.title, task_path(task) %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= @task.errors.full_messages.join(", ") %>

<%= form_for @task do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <%= f.label :project_id %>
    <%= f.text_field :project_id %>
  </div>

  <div>
    <%= f.label :due_date %>
    <%= f.datetime_field :due_date %>
  </div>

  <%= f.submit %>

<% end %>

app/views/tasks/show.html.erb
<div class="container-project">

<h1><%= @task.title%></h1>
<p><%= @task.project_id %></p>
<p><%= @task.due_date %></p>
<%= link_to "Edit", edit_task_path(@task) %>
<%= link_to "Delete", task_path(@task), method: :delete,
                                  data: {confirm: "Are you sure?"}%>