config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :discussions
    resources :memberships, only: [:create, :destroy]
  end

  namespace :discussions do
    resources :comments
  end

  post "/tasks/status_change/:id" => "tasks#status_change", as: :status_change_task

  get "/about" => "home#about"

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user;

  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy

  has_many :memberships, dependent: :destroy
  has_many :member_users, through: :memberships, source: :user

  validates :title, presence: true, uniqueness: true
  validates :user_id, uniqueness: {scope: :project_id}

  def membership_for(user)
    memberships.find_by_user_id user if user
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      #render text: "SUCCESS"
      redirect_to project_path(@project)
    else
      #render text: "FAILURE"
      render :new
    end
  end

  def show
    @task = Task.new
    #puts "===================== inside project controller show"

  end

  def index
    @projects = Project.all
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def find_project
    @project = Project.find params[:id]
  end

  def project_params
    project_params = params.require(:project).permit([:title, :description, :due_date])
  end

  def membership_for_project
    @membership ||= @project.membership_for(current_user)
  end
  helper_method :membership_for_project

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= @project.errors.full_messages.join(", ") %>

<%= form_for @project do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :due_date %>
    <%= f.datetime_field :due_date %>
  </div>

  <%= f.submit %>

<% end %>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<% @projects.each do |project| %>
  <div>
    <%= link_to "Project #{project.id}: " + project.title + " --- Joined (#{project.memberships.count})", project_path(project) %>
  </div>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= @project.errors.full_messages.join(", ") %>

<%= form_for @project do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :due_date %>
    <%= f.datetime_field :due_date %>
  </div>

  <%= f.submit %>

<% end %>

app/views/projects/show.html.erb
<h1>Project: <%= @project.title %></h1>
<p><%= @project.description %></p>
<p><%= @project.due_date %></p>
<p>Members: <%= @project.member_users.map(&:full_name).join(", ") %></p>
<%= link_to "Edit", edit_project_path(@project) %>
|
<%= link_to "Delete", project_path(@project), method: :delete,
                                  data: {confirm: "Are you sure?"}%>
|
<%= link_to "Discussions", project_discussions_path(@project) %>

<%# only show the Join/Leave for people other than the idea creator %>
<% if @project.user != current_user %>
  |
  <% if membership_for_project %>
    <%= link_to "Leave", project_membership_path(@project, membership_for_project), method: :delete %>
  <% else %>
    <%= link_to "Join", project_memberships_path(@project), method: :post %>
  <% end %>
  (<%= @project.memberships.count %>)
<% end %>

<hr>
<%# this is for displaying the @task validation error for creating tasks  %>
<%= @task.errors.full_messages.join(", ") %>

<hr>

<div class="row">

  <div class="col-xs-12">
    <div class="support-header">
      <h1>Tasks</h1>

      <form action="/tasks/search" method="GET" class="search-group">
        <input type="text" name="search" class="txt-search" value="">
        <input type="submit" value="Search" class="btn btn-primary btn-search">
      </form>
    </div>

  </div>

</div>

<%#= paginate(@tasks) %>
<div class="pagination_info">
  <%#= page_entries_info @tasks %>
</div>

<table class="table table-medium">
  <thead>
    <tr>
      <th class="col-md-2">Title</th>
      <th class="col-md-2">Body</th>
      <th class="col-md-2">Due Date</th>
      <th class="col-md-6">Actions</th>
    </tr>
  </thead>

  <tbody>

    <% @project.tasks.order("due_date DESC").each do |task| %>

    <tr>
       <td><%= task.title %></td>
       <td class="message--shorten"><%= task.body %></td>
       <td><%= task.due_date %></td>
       <td>
          <div class="btn-group btn-group--edit-delete-status">
            <%= button_to "Edit", edit_project_task_path(@project,task), method: :get, class: 'btn btn-primary btn-edit'  %>
            <%= button_to "Delete",project_task_path(@project,task), method: :delete,
                                                     data: {confirm: "Are you sure?"},
                                                     class: 'btn btn-secondary btn-primary'%>
            <% btn_status = (task.status == "Done")? "btn-status-done" : "btn-status-not-done" %>
            <%= button_to task.status, status_change_task_path(task), method: :post,
                                                    class: "btn btn-primary #{btn_status}"%>
          </div>
       </td>
    </tr>

    <% end %>

 </tbody>


</table>


<%#= paginate(@tasks) %>
<h2> New Task </h2>
<%= form_for @task, url: project_tasks_path(@project), html: {class: "form"} do |f| %>

  <div class="form-group">
    <%= f.label :title, "Title", class: "control-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group project-task">
    <%= f.label :body, "Body", class: "control-label" %>
    <%= f.text_area :body, class: "form-control project-task__textarea" %>
  </div>

  <div class="form-group">
    <%= f.label :due_date, "Due Date", class: "control-label" %>
    <%= f.text_field :due_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Task", class: "btn btn-primary" %>
  </div>
<% end %>


</div>