config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :discussions
    resources :memberships, only: [:create, :destroy]
  end

  namespace :discussions do
    resources :comments
  end

  post "/tasks/status_change/:id" => "tasks#status_change", as: :status_change_task

  get "/about" => "home#about"

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%# font awesome %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
</head>
<body>

  <%# Testing Boot Strap css and js %>
    <%# <button class="btn-primary">My button</button>
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
          <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
          <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
          <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="home">...</div>
          <div role="tabpanel" class="tab-pane" id="profile">...</div>
          <div role="tabpanel" class="tab-pane" id="messages">...</div>
          <div role="tabpanel" class="tab-pane" id="settings">...</div>
        </div>

      </div> %>
    <%# End Testing Boot Strap css and js %>

  <%= link_to "Home", root_path  %>
  |
  <%= link_to "About", about_path %>
  |
  <%= link_to "New Project", new_project_path %>
  |
  <%= link_to "All Projects", projects_path %>

  |===|
<% if user_signed_in? %>
  <%= "Hello #{current_user.first_name}" %>
  |
  <%= link_to "Edit Profile", edit_user_path(current_user) %>
  |
  <%= link_to "Log out", sessions_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_path %>
  |
  <%= link_to "Sign up", new_user_path %>
<% end %>

  <hr>
  <%= flash[:notice] || flash[:alert] %>
  <hr>
<%= yield %>

</body>
</html>